### ISSUE TITLE
The received access token is not valid

### ISSUE THREAD

**Issue by michalklempa** [MSOpenTech/vagrant-azure#140]
Hi,
I am getting into trouble while trying to start my VM.
I have followed https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/ although I am supposed to use 'classic' portal, which is not accessible to me.
I have created Application, delegated privileges to user, found tenant and created key with secret.
Put all together to a Vagrantfile and I am getting error:

```
$ vagrant up --provider=azure
Bringing machine 'devops-vagrant-azure-01' up with 'azure' provider...
==> devops-vagrant-azure-01: Launching an instance with the following settings...
==> devops-vagrant-azure-01:  -- Management Endpoint: https://management.azure.com
==> devops-vagrant-azure-01:  -- Subscription Id: 3dae5af8-79af-4fe7-8b36-...
==> devops-vagrant-azure-01:  -- Resource Group Name: lively-smoke-54
==> devops-vagrant-azure-01:  -- Location: northeurope
==> devops-vagrant-azure-01:  -- VM Name: still-silence-92
==> devops-vagrant-azure-01:  -- VM Size: Small
==> devops-vagrant-azure-01:  -- Image URN: canonical:ubuntuserver:16.04.0-DAILY-LTS:latest
/home/michalklempa/.vagrant.d/gems/gems/azure_mgmt_compute-0.2.1/lib/azure_mgmt_compute/virtual_machine_images.rb:139:in `block in list': { (MsRestAzure::AzureOperationError)
  "message": "MsRestAzure::AzureOperationError",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions",
    "method": "get",
    "path_params": {
      "location": "northeurope",
      "publisherName": "canonical",
      "offer": "ubuntuserver",
      "skus": "16.04.0-DAILY-LTS",
      "subscriptionId": "3dae5af8-79af-4fe7-8b36-..."
    },
    "skip_encoding_path_params": null,
    "query_params": {
      "$filter": null,
      "$top": null,
      "$orderby": null,
      "api-version": "2015-06-15"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "x-ms-client-request-id": "7573f277-a5af-4f35-8419-a70f31a86e1c",
      "accept-language": "en-US"
    },
    "body": null,
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      [
        "cookie_jar"
      ]
    ],
    "log": null
  },
  "response": {
    "body": "{\"error\":{\"code\":\"InvalidAuthenticationToken\",\"message\":\"The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "x-ms-failure-cause": "gateway",
      "x-ms-request-id": "4575776a-1490-49c7-92e4-b7a67bb9d279",
      "x-ms-correlation-request-id": "4575776a-1490-49c7-92e4-b7a67bb9d279",
      "x-ms-routing-request-id": "UKSOUTH2:20160928T081233Z:4575776a-1490-49c7-92e4-b7a67bb9d279",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Wed, 28 Sep 2016 08:12:32 GMT",
      "connection": "close",
      "content-length": "281"
    },
    "status": 401
  }
}
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/promise.rb:497:in `call'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/promise.rb:497:in `block in on_fulfill'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/promise.rb:527:in `block in realize'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
    from /home/michalklempa/.vagrant.d/gems/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

```

**Comment by scottmmeyer** [comment]
I am getting the same error.  For classic portal, did you navigate to https://manage.windowsazure.com/

**Comment by devigned** [comment]
Please setup a service principle via https://github.com/Azure/vagrant-azure/issues/127#issuecomment-276844766. I think it will simplify the process greatly.

Please post back with results.
