### ISSUE TITLE
Error with 2.0.0pre4

### ISSUE THREAD

**Issue by gabidombrowski** [MSOpenTech/vagrant-azure#169]
Installed 2.0.0pre4 with `vagrant plugin install vagrant-azure --plugin-version '2.0.0.pre4'` and am getting errors.

I've tried both a `sudo gem update` and `sudo gem cleanup` as well.
```
➜  remote-dev git:(master) ✗ vagrant plugin list
vagrant-azure (2.0.0.pre4)
  - Version Constraint: 2.0.0.pre4
vagrant-hostmanager (1.8.5)
vagrant-share (1.1.6, system)
```
```
➜  remote-dev git:(master) ✗ vagrant up --provision
/Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:15:in `<class:AzureResourceManager>': uninitialized constant VagrantPlugins::Azure::VERSION (NameError)
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:13:in `<module:Services>'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:12:in `<module:Azure>'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:11:in `<module:VagrantPlugins>'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:10:in `<top (required)>'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action/connect_azure.rb:4:in `require_relative'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action/connect_azure.rb:4:in `<top (required)>'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:94:in `block in action_read_state'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:92:in `tap'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:92:in `action_read_state'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/provider.rb:28:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:188:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
    from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/provider.rb:48:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:506:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:145:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:669:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:131:in `install_providers'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:85:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

Also getting an error on an update:
```
➜  remote-dev git:(master) ✗ vagrant plugin update vagrant-azure
Updating plugins: vagrant-azure. This may take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.99.3, already activated mime-types-3.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:126:in `update'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:118:in `update_plugins'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/update_gems.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/update.rb:23:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

**Comment by devigned** [comment]
This is what I'm seeing when installing. It sounds like you have some conflicting gems. It might be that you are using sudo to install the plugin and transitively the gems.

```
$ vagrant plugin install vagrant-azure --plugin-version '2.0.0.pre4'
Installing the 'vagrant-azure --version '2.0.0.pre4'' plugin. This can take a few minutes...
Fetching: multipart-post-2.0.0.gem (100%)
Fetching: faraday-0.11.0.gem (100%)
Fetching: concurrent-ruby-1.0.5.gem (100%)
Fetching: timeliness-0.3.8.gem (100%)
Fetching: ms_rest-0.6.3.gem (100%)
Fetching: faraday-cookie_jar-0.0.6.gem (100%)
Fetching: ms_rest_azure-0.6.2.gem (100%)
Fetching: highline-1.7.8.gem (100%)
Fetching: haikunator-1.1.0.gem (100%)
Fetching: azure_mgmt_storage-0.8.0.gem (100%)
Fetching: azure_mgmt_network-0.8.0.gem (100%)
Fetching: azure_mgmt_compute-0.8.0.gem (100%)
Fetching: azure_mgmt_resources-0.8.0.gem (100%)
Fetching: vagrant-azure-2.0.0.pre4.gem (100%)
Installed the plugin 'vagrant-azure (2.0.0.pre4)'!
```

My gem directory looks like this after install:
```
$ ls ~/.vagrant.d/gems/2.2.5/gems/
azure_mgmt_compute-0.8.0/   azure_mgmt_storage-0.8.0/   faraday-cookie_jar-0.0.6/   ms_rest-0.6.3/              timeliness-0.3.8/
azure_mgmt_network-0.8.0/   concurrent-ruby-1.0.5/      haikunator-1.1.0/           ms_rest_azure-0.6.2/        vagrant-azure-2.0.0.pre4/
azure_mgmt_resources-0.8.0/ faraday-0.11.0/             highline-1.7.8/             multipart-post-2.0.0/
```

**Comment by gabidombrowski** [comment]
Ok, my gem directory looks the same. Do you think this error is likely related to the same thing?

/Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:15:in `<class:AzureResourceManager>': uninitialized constant VagrantPlugins::Azure::VERSION (NameError)

**Comment by devigned** [comment]
I think I've found the issue. I should get a new gem out today.

**Comment by devigned** [comment]
Fix should be out there in pre5. Please reopen if this doesn't work for you.

**Comment by gabidombrowski** [comment]
Hi! Still seeing the same error. I did a `sudo gem update` and `sudo gem cleanup`.

```
/Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/services/azure_resource_manager.rb:15:in `<class:AzureResourceManager>': uninitialized constant VagrantPlugins::Azure::VERSION (NameError)
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/services/azure_resource_manager.rb:13:in `<module:Services>'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/services/azure_resource_manager.rb:12:in `<module:Azure>'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/services/azure_resource_manager.rb:11:in `<module:VagrantPlugins>'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/services/azure_resource_manager.rb:10:in `<top (required)>'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/action/connect_azure.rb:4:in `require_relative'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/action/connect_azure.rb:4:in `<top (required)>'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/action.rb:94:in `block in action_read_state'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/action.rb:92:in `tap'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/action.rb:92:in `action_read_state'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/provider.rb:28:in `action'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:188:in `block in action'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
  from /Users/user/.vagrant.d/gems/2.2.5/gems/vagrant-azure-2.0.0.pre5/lib/vagrant-azure/provider.rb:48:in `state'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:506:in `state'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:145:in `initialize'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `new'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/vagrantfile.rb:79:in `machine'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:669:in `machine'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:131:in `install_providers'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/up/command.rb:85:in `execute'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
  from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

**Comment by devigned** [comment]
My fault... I've reopened the issue and will have a gem out shortly.
