### ISSUE TITLE
No synced folder implementation is available for your synced folders!

### ISSUE THREAD

**Issue by IvanBoyko** [MSOpenTech/vagrant-azure#170]
I've followed all the steps and used your Vagrantfile example for **Windows**.
When I run `vagrant up --provider=azure` I get the following error:

> Bringing machine 'default' up with 'azure' provider...
> No synced folder implementation is available for your synced folders!
> Please consult the documentation to learn why this may be the case.
> You may force a synced folder implementation by specifying a "type:"
> option for the synced folders. Available synced folder implementations
> are listed below.
> 
> docker, nfs, rsync, smb, virtualbox

This is for plugin version '2.0.0.pre3' as it's still stated in the README.
Tried also with '2.0.0.pre4' but it failed with a different error.

**Comment by devigned** [comment]
- fixed the readme. thx u!
- I believe this should fallback on using winrm to transfer files. Can you run with --debug and post back?

**Comment by IvanBoyko** [comment]
With version '2.0.0.pre4' I get the following:

```
C:\>vagrant up --provider=azure
D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:15:in `<class:AzureResourceManager>':
uninitialized constant VagrantPlugins::Azure::VERSION (NameError)
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:13:in `<module:Services>'

        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:12:in `<module:Azure>'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:11:in `<module:VagrantPlu
gins>'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/services/azure_resource_manager.rb:10:in `<top (required)>'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action/connect_azure.rb:4:in `require_relative'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action/connect_azure.rb:4:in `<top (required)>'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:94:in `block in action_read_state'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:92:in `tap'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/action.rb:92:in `action_read_state'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/provider.rb:28:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:188:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `action'
        from D:/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre4/lib/vagrant-azure/provider.rb:48:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:504:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:145:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:201:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:183:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/up/command.rb:131:in `install_providers'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/up/command.rb:85:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'
```

If I run the same with --debug it gives quite a lot of output.
Do you still want me to post it here?

**Comment by IvanBoyko** [comment]
Just guessing - I don't have Azure CLI installed, is this a prerequisite?

**Comment by devigned** [comment]
Nope. Azure CLI doesn't need to be in installed.

**Comment by dcallagh** [comment]
I have this issue too, with pre6

**Comment by wsmckenz** [comment]
You can work around this by disabling the shared folder.

Vagrant.configure('2') do |config|
  config.vm.box = 'azure'
  config.vm.synced_folder ".", "/vagrant", disabled: true
