### ISSUE TITLE
error on executing vagrant up with provider azure on Mac OS Sierra

### ISSUE THREAD

**Issue by saifmulla** [MSOpenTech/vagrant-azure#181]
I have followed all the instructions from the repository in order to start a virtual machine on Azure cloud from my Mac however on executing `vagrant up --provider=azure` I keep getting the following errors which I am unable to resolve, I was wondering if someone could help me with this, Thanks 
Here is the log for all the errors generated on Mac

```
/Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:49:in `merge!': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:60:in `merge'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:52:in `block in merge!'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:49:in `each'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:49:in `merge!'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/options.rb:60:in `merge'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday/connection.rb:61:in `initialize'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday.rb:67:in `new'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/faraday-0.12.0.1/lib/faraday.rb:67:in `new'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/ms_rest-0.6.3/lib/ms_rest/http_operation_request.rb:71:in `block in run_promise'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/promise.rb:531:in `block in realize'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	from /Users/saifmulla/.vagrant.d/gems/2.2.5/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by saifmulla** [comment]
Moreover here are the settings I am using to configure in my Vagrantfile
``` ruby
config.vm.box = "azure"
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end
```

**Comment by njappboy** [comment]
Seeing the exact same issue. Just started. Happens when I call `vagrant destroy -f`.

**Comment by njappboy** [comment]
Happening on El Capitan in my case.
`vagrant` seems to be running fine. The `2.0.0pre6` version of `vagrant-azure` plugin seems to be loading as well. When I don't provide environment inputs I'm properly and promptly warned:
```
Microsoft Azure Provider:
* You must provide an Azure Subscription Id either through ENV['AZURE_SUBSCRIPTION_ID'] or via Vagrantfile.
* You must provide Azure Active Directory Tenant ID, Application Client ID and Application Client Secret via ENV or Vagrantfile.
```

**Comment by njappboy** [comment]
`.vagrant.d/gems/2.2.5/gems/ms_rest-0.6.3/lib/ms_rest/http_operation_request.rb:71:in `block in run_promise'` could be a call to the azure api.

**Comment by devigned** [comment]
Grab v2.0.0.pre7 and this should be mitigated. We'll update to the latest ms_rest when released.
