### ISSUE TITLE
Vagrant-Azure plugin install fails on Vagrant 1.9.7

### ISSUE THREAD

**Issue by jacobnosal** [MSOpenTech/vagrant-azure#197]
## Relevant parameters:
OS: macOS Sierra - 10.12.6
```bash
vagrant --version
Vagrant 1.9.7
```

## Expected Behavior
Successful installation of the `vagrant-azure` plugin.

## Observed Behavior
Installation times out.

### Error message:
```bash
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
```
## Steps to reproduce
Run the following command
```bash
vagrant plugin install vagrant-azure --debug
```

## Debug ouput
```bash
jacob$ vagrant plugin install vagrant-azure --debug
 INFO global: Vagrant version: 1.9.7
 INFO global: Ruby version: 2.3.4
 INFO global: RubyGems version: 2.5.2
 INFO global: VAGRANT_OLD_ENV_HOME="/Users/jacob"
 INFO global: VAGRANT_OLD_ENV_PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jacob/bin"
 INFO global: VAGRANT_OLD_ENV_PWD="/Users/jacob"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_OLD_ENV_TMPDIR="/var/folders/bc/4x3649bd6p98yq49vh5_3s6m0000gn/T/"
 INFO global: VAGRANT_OLD_ENV_TERM_SESSION_ID="C6B32442-2F37-40B3-BC28-7A997618B7C9"
 INFO global: VAGRANT_OLD_ENV_SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.iW2hb2iSHl/Listeners"
 INFO global: VAGRANT_OLD_ENV___CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
 INFO global: VAGRANT_OLD_ENV_LOGNAME="jacob"
 INFO global: VAGRANT_OLD_ENV_Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.NA0iiJw8c6/Render"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_OLD_ENV_LANG="en_US.UTF-8"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_TERM="xterm-256color"
 INFO global: VAGRANT_OLD_ENV__="/usr/local/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_SHLVL="1"
 INFO global: VAGRANT_OLD_ENV_XPC_FLAGS="0x0"
 INFO global: VAGRANT_OLD_ENV_XPC_SERVICE_NAME="0"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_OLD_ENV_TERM_PROGRAM_VERSION="388.1.1"
 INFO global: VAGRANT_OLD_ENV_USER="jacob"
 INFO global: VAGRANT_OLD_ENV_TERM_PROGRAM="Apple_Terminal"
 INFO global: VAGRANT_OLD_ENV_SHELL="/bin/bash"
 INFO global: VAGRANT_NO_PLUGINS="1"
 INFO global: VAGRANT_DISABLE_PLUGIN_INIT="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - vagrant-share = [installed: undefined constraint: > 0]
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/validate/plugin.rb
 INFO manager: Registered plugin: validate command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/winssh/plugin.rb
 INFO manager: Registered plugin: windows ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/amazon/plugin.rb
 INFO manager: Registered plugin: Amazon Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/bsd/plugin.rb
 INFO manager: Registered plugin: BSD-based guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/dragonflybsd/plugin.rb
 INFO manager: Registered plugin: DragonFly BSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/elementary/plugin.rb
 INFO manager: Registered plugin: Elementary guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/kali/plugin.rb
 INFO manager: Registered plugin: Kali guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/trisquel/plugin.rb
 INFO manager: Registered plugin: Trisquel guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Plugin loading is currently disabled.
 INFO vagrant: `vagrant` invoked: ["plugin", "install", "vagrant-azure", "--debug"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000102812e20>)
 INFO environment:   - cwd: /Users/jacob
 INFO environment: Home path: /Users/jacob/.vagrant.d
DEBUG environment: Effective local data path: 
 WARN environment: No local data path is set. Local data cannot be stored.
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x00000100c14980>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x00000100ac4ad0>
 INFO cli: CLI: [] "plugin" ["install", "vagrant-azure"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandPlugin::Command::Root ["install", "vagrant-azure"]
DEBUG root: Invoking command class: VagrantPlugins::CommandPlugin::Command::Install ["vagrant-azure"]
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /Users/jacob>]
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
 INFO host: Detected: darwin!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action:  #<Vagrant::Action::Builder:0x00000100dfdb70>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x00000102071d38>
 INFO interface: info: Installing the 'vagrant-azure' plugin. This can take a few minutes...
Installing the 'vagrant-azure' plugin. This can take a few minutes...
DEBUG bundler: Enabling strict dependency enforcement
DEBUG bundler: Dependency list for installation:
 - vagrant-share > 0
 - vagrant-azure > 0
 - bigdecimal = 1.2.8
 - builder = 3.2.3
 - childprocess = 0.6.3
 - domain_name = 0.5.20170404
 - erubis = 2.7.0
 - ffi = 1.9.18
 - gssapi = 1.2.0
 - gyoku = 1.3.1
 - hashicorp-checkpoint = 0.1.4
 - http-cookie = 1.0.3
 - httpclient = 2.8.3
 - i18n = 0.8.0
 - io-console = 0.4.5
 - json = 1.8.3
 - listen = 3.1.5
 - little-plugger = 1.1.4
 - log4r = 1.1.10
 - logging = 2.2.2
 - mime-types = 3.1
 - mime-types-data = 3.2016.0521
 - multi_json = 1.12.1
 - net-scp = 1.2.1
 - net-sftp = 2.1.2
 - net-ssh = 4.1.0
 - netrc = 0.11.0
 - nori = 2.6.0
 - pkg-config = 1.1.9
 - psych = 2.1.0
 - rb-fsevent = 0.10.2
 - rb-inotify = 0.9.10
 - rb-kqueue = 0.2.5
 - rdoc = 4.2.1
 - rest-client = 2.0.2
 - ruby_dep = 1.3.1
 - rubyntlm = 0.6.2
 - rubyzip = 1.2.1
 - unf = 0.1.4
 - unf_ext = 0.0.7.4
 - vagrant = 1.9.7
 - wdm = 0.1.1
 - winrm = 2.2.3
 - winrm-elevated = 1.1.0
 - winrm-fs = 1.0.1
DEBUG bundler: Enabling user defined remote RubyGems sources
DEBUG bundler: Enabling default remote RubyGems sources
DEBUG bundler: Adding source - https://rubygems.org/
DEBUG bundler: Adding source - https://gems.hashicorp.com/
ERROR bundler: Failed to load configured plugin source `#<Gem::Source:0x00000100e35110>`: timed out (https://gems.hashicorp.com/specs.4.8.gz)
ERROR warden: Error occurred: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x00000102071d38>
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000011058acf8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PluginSourceError: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/>
ERROR vagrant: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:359:in `rescue in block in validate_configured_sources!'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:350:in `block in validate_configured_sources!'
/opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
/opt/vagrant/embedded/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:349:in `validate_configured_sources!'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:285:in `internal_install'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/bundler.rb:106:in `install'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/action/install_gem.rb:29:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/base.rb:14:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:32:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:31:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/install.rb:31:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/commands/plugin/command/root.rb:66:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/environment.rb:308:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/bin/vagrant:138:in `<main>'
 INFO interface: error: Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
 INFO interface: Machine: error-exit ["Vagrant::Errors::PluginSourceError", "Vagrant failed to load a configured plugin source. This can be caused\nby a variety of issues including: transient connectivity issues, proxy\nfiltering rejecting access to a configured plugin source, or a configured\nplugin source not responding correctly. Please review the error message\nbelow to help resolve the issue:\n\n  timed out (https://gems.hashicorp.com/specs.4.8.gz)\n\nSource: https://gems.hashicorp.com/"]
```

## Other notes
```bash
jacob$ wget -v https://gems.hashicorp.com/specs.4.8.gz
--2017-08-04 08:59:05--  https://gems.hashicorp.com/specs.4.8.gz
Resolving gems.hashicorp.com... 2600:9000:2009:cc00:b:36d6:3540:93a1, 2600:9000:2009:2a00:b:36d6:3540:93a1, 2600:9000:2009:6800:b:36d6:3540:93a1, ...
Connecting to gems.hashicorp.com|2600:9000:2009:cc00:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:2a00:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:6800:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:3a00:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:d600:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:5200:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:ce00:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|2600:9000:2009:5800:b:36d6:3540:93a1|:443... failed: Operation timed out.
Connecting to gems.hashicorp.com|54.192.122.248|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 281 [binary/octet-stream]
Saving to: ‘specs.4.8.gz.1’

specs.4.8.gz.1                          100%[============================================================================>]     281  --.-KB/s    in 0s      

2017-08-04 09:09:09 (29.8 MB/s) - ‘specs.4.8.gz.1’ saved [281/281]
```
and
```bash
jacob$: wget -4 https://gems.hashicorp.com/specs.4.8.gz
--2017-08-04 09:27:30--  https://gems.hashicorp.com/specs.4.8.gz
Resolving gems.hashicorp.com... 54.192.122.235, 54.192.122.125, 54.192.122.229, ...
Connecting to gems.hashicorp.com|54.192.122.235|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 281 [binary/octet-stream]
Saving to: ‘specs.4.8.gz.2’

specs.4.8.gz.2                          100%[============================================================================>]     281  --.-KB/s    in 0s      

2017-08-04 09:27:30 (17.9 MB/s) - ‘specs.4.8.gz.2’ saved [281/281]```

**Comment by bryanwb** [comment]
@jacobnosal did you try installing 2.0.0.pre8?
```
vagrant plugin install vagrant-azure --plugin-version '2.0.0.pre8'
```
I am having success w/ it + vagrant 1.9.8 on Mac OS X

**Comment by jacobnosal** [comment]
@bryanwb worked like a charm. Curious what the issue was to begin with but appreciate the resolution.
